### ISSUE TITLE
is broken in blender 3.0

### ISSUE THREAD

**Issue by SlincHD** [jlampel/extra_lights#26] opened 2022-01-10 21:53 UTC
all of the values not working at all in 3.0

**Comment by jlampel** [comment] 2022-01-10 23:49
Hi, thank you for the report! I just tested in 3.0 and 3.1 alpha and am not seeing the issue. Can you please be more specific?

**Comment by R-yber** [comment] 2022-06-06 11:49
For me the sun lights are not working correctly along with their corresponding environmental setups. For example, if I select a moon light, only the standard light settings in cycles show up and not the ones specially developed. Also the environmental texture and colour management settings do not adjust depending on the type of sun light you use. Any idea on what might be up?

**Comment by jlampel** [comment] 2022-06-06 16:57
I just ran through some tests, and it seems like everything is working normally on my end. When you add a light, do you have these three options checked in the redo panel? They need to be turned on in order to get those effects. 
![image](https://user-images.githubusercontent.com/12982300/172208426-5713f310-9d8f-4436-990c-0bc329224770.png)

**Comment by maxfahl** [comment] 2022-06-30 06:41
I have no lights in my add menu on 3.2, someone else experiencing this?

**Comment by jlampel** [comment] 2022-06-30 16:08
I can confirm that it still works in Blender 3.2. Try installing again, and if that doesn't work, please share a screenshot of your add lights menu and what the add-on looks like in your user preferences.

**Closed** 2022-06-30 16:19 UTC
